routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'AuthController@showLoginForm')->name('login');
Route::post('/login', 'AuthController@loginProcess')->name('login.process');
Route::post('/logout', 'AuthController@logoutProcess')->name('logout.process');

Route::group(['middleware' => 'auth'], function() {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/employee', 'EmployeeController')->middleware('admin');
    
    // Route::view('/p', 'employee.permission');
    // Route::get('/pdf', function () {
    //     $pdf = PDF::loadView('attendance.pdf', []);
	//     return $pdf->stream('document.pdf');
    // });

    Route::get('/attendance', 'AttendanceController@getAttendances')->name('attendance');
    Route::post('/attendance/receive', 'AttendanceController@attendanceStore')->name('attendance.receive');
    Route::get('/attendance/search', 'AttendanceController@attendanceSearch')->name('attendance.search');

    Route::get('/profile', 'EmployeeController@profile')->name('employee.profile');
    Route::post('/password-reset', 'EmployeeController@resetPassword')->name('password.new');
    Route::post('/image/change', 'EmployeeController@imageChange')->name('employee.image.change');

    Route::resource('/customer', 'CustomerController');
    Route::get('/customer/{id}/approve', 'CustomerController@approve')->name('customer.approve');

    Route::resource('/project', 'CustomerProjectController');

    Route::get('/setup/types', 'CustomerTypeController@index')->name('customer.types');
    Route::post('/setup/type/store', 'CustomerTypeController@store')->name('customer.type.store');
    Route::get('/setup/type/{id}/edit', 'CustomerTypeController@edit')->name('customer.type.edit');
    Route::post('/setup/type/update', 'CustomerTypeController@update')->name('customer.type.update');
    Route::delete('/setup/type/{id}/delete', 'CustomerTypeController@destroy')->name('customer.type.delete');

    Route::resource('/product', 'ProductController');

    Route::get('/visits', 'VisitController@index')->name('visits');
    Route::get('/visit/create', 'VisitController@create')->name('visit.create');
    Route::post('/visit/store', 'VisitController@store')->name('visit.store');
    Route::get('/visit/{id}/show', 'VisitController@show')->name('visit.show');
    Route::get('/visit/{id}/edit', 'VisitController@edit')->name('visit.edit');
    Route::put('/visit/update', 'VisitController@update')->name('visit.update');
    Route::delete('/visit/{id}/destroy', 'VisitController@destroy')->name('visit.destroy');

    Route::get('/orders/{with_details?}', 'OrderController@index')->name('orders');
    Route::get('/order/create', 'OrderController@create')->name('order.create');
    Route::post('/order/confirm', 'OrderController@confirmOrder')->name('order.confirm');
    Route::get('/order/{id}/invoice', 'OrderController@invoice')->name('order.invoice');

    Route::get('/order/{id}/show', 'OrderController@show')->name('order.show');
    Route::get('/order/{id}/edit', 'OrderController@edit')->name('order.edit');
    Route::post('/order/update', 'OrderController@update')->name('order.update');
    Route::post('/order/delete', 'OrderController@destroy')->name('order.destroy');

    Route::get('/order/{id}/delivery', 'OrderDeliveryController@deliveryForm')->name('order.delivery');
    Route::post('/order/delivery', 'OrderDeliveryController@deliveryProcess')->name('order.delivery.process');

    // oid = order id, bid = delivery batch id
    Route::get('/order/{oid}/{bid}/chalan', 'OrderDeliveryController@chalan')->name('order.delivery.chalan');

    Route::get('/pending-orders', 'OrderController@pending')->name('order.pending');
    Route::get('/archive-orders', 'OrderController@archive')->name('order.archive');

    Route::group(['middleware'=>'admin'], function() {

        Route::resource('/setup/post', 'EmployeePostController')->except('show');
        Route::resource('/setup/department', 'EmployeeDepartmentController')->except('show');
        Route::resource('/setup/company', 'CompanyController')->except('show');
        
        Route::get('/settings', 'SettingsController@otherSettings')->name('settings');
        Route::post('/settings/update', 'SettingsController@settingsUpdate')->name('settings.update');

        Route::get('/setup/transports', 'TransportModeController@index')->name('transports');
        Route::post('/setup/transport/store', 'TransportModeController@store')->name('transport.store');
        Route::get('/setup/transport/{id}/edit', 'TransportModeController@edit')->name('transport.edit');
        Route::post('/setup/transport/update', 'TransportModeController@update')->name('transport.update');
        Route::delete('/setup/transport/{id}/delete', 'TransportModeController@destroy')->name('transport.delete');

        Route::get('/setup/job-types', 'JobTypeController@index')->name('job.types');
        Route::post('/setup/job-type/store', 'JobTypeController@store')->name('job.type.store');
        Route::get('/setup/job-type/{id}/edit', 'JobTypeController@edit')->name('job.type.edit');
        Route::post('/setup/job-type/update', 'JobTypeController@update')->name('job.type.update');
        Route::delete('/setup/job-type/{id}/delete', 'JobTypeController@destroy')->name('job.type.delete');
    });

    Route::get('/report/visit-report', 'ReportController@visitReport')->name('report.visit-report');
    Route::get('/report/visit', 'ReportController@visitReportProcess')->name('report.visit');

    Route::get('/report/order-report', 'ReportController@orderReport')->name('report.order-report');
    Route::post('/report/order', 'ReportController@orderReportProcess')->name('report.order');

});

app/Models/CustomerProject.php
<?php

namespace App\Models;

use App\Models\Customer;
use Illuminate\Database\Eloquent\Model;

class CustomerProject extends Model
{
    protected $fillable = ['customer_id', 'project_name', 'project_description', 'isDelete', 'saved_by'];

    public function customer() {
        return $this->belongsTo(Customer::class);
    }
}

app/Http/Controllers/Api/CustomerProjectController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Customer;
use Illuminate\Http\Request;
use App\Models\CustomerProject;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class CustomerProjectController extends Controller
{
    public function getprojects($customerId) {
        $customer_projects = CustomerProject::where('customer_id', $customerId)->where('isDelete', 0)->get();
        if ($customer_projects->count() > 0) {
            return response()->json([
                'success' => true,
                'data' => $customer_projects
            ]);
        }
        return response()->json([
            'success' => false,
            'message' => 'Project List not found'
        ]);
    }

    public function storeProjectInfo(Request $request) {
        
        $validator = Validator::make($request->all(), [
            'customer' => 'required|numeric',
            'project_name' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'message' => $validator->errors()
            ]);
        }

        try {
            CustomerProject::create([
                'customer_id' => $request->customer,
                'project_name' => $request->project_name,
                'project_description' => $request->project_description,
                'saved_by' => app('currentUserId')
            ]);
            
            return response()->json([
                'success' => true,
                'message' => 'Customer project save successfully.'
            ]);

        } catch (\Exception $e) {
            
            return response()->json([
                'success' => false,
                'message' => $e->getMessage()
            ]);
        }
    }
}

app/Http/Controllers/CustomerProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use Illuminate\Http\Request;
use App\Models\CustomerProject;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class CustomerProjectController extends Controller
{
    public function index() {
        if ($this->isAdmin()) {
            $customer_projects = CustomerProject::where('isDelete', 0)->latest()->get();
        } else {
            $customer_projects = CustomerProject::where('isDelete', 0)
            ->where('saved_by', Auth::id())->latest()->get();
        }
        return view('customer_project.index', compact('customer_projects'));
    }

    public function create() {
        $customers = $this->getCustomers();
        return view('customer_project.create', compact('customers'));
    }

    private function getCustomers() {
        if ($this->isAdmin()) {
            $customers = Customer::where('isDelete', 0)->get();
        } else {
            $customers = Customer::where('isDelete', 0)->get();
        }
        return $customers;
    }

    public function store(Request $request) {
        $request->validate([
            'customer' => 'required|numeric',
            'project_name' => 'required'
        ]);

        try {
            CustomerProject::create([
                'customer_id' => $request->customer,
                'project_name' => $request->project_name,
                'project_description' => $request->project_description,
                'saved_by' => Auth::id()
            ]);
            $this->message('success', 'Project info save successfully.');
        } catch (\Exception $e) {
            $this->message('error', $e->getMessage());
        }
        return redirect()->route('project.index');
    }

    public function edit($id) {
        $project = CustomerProject::findOrFail($id);
        if ($this->isOwn($project->customer->saved_by) || $this->isAdmin()) {
            $customers = $this->getCustomers();
            return view('customer_project.edit', compact('project', 'customers'));
        }
        abort(403);
    }

    public function update(Request $request, $id) {
        $request->validate([
            'customer' => 'required|numeric',
            'project_name' => 'required'
        ]);

        $project = CustomerProject::findOrFail($id);
        try {
            $project->customer_id = $request->customer;
            $project->project_name = $request->project_name;
            $project->project_description = $request->project_description;
            $project->save();

            $this->message('success', 'Project info update successfully.');
        } catch (\Exception $e) {
            $this->message('error', $e->getMessage());
        }
        return redirect()->route('project.index');
    }

    public function show() {

    }

    public function destroy($id) {
        if (Gate::allows('admin-only', Auth::user())) {
            try {
                $project = CustomerProject::findOrFail($id);
                $project->isDelete = 1;
                $project->save();
    
                $this->message('success', 'Project info delete successfully');
            } catch (\Exception $e) {
                $this->message('error', $e->getMessage());
            }
            return redirect()->route('project.index');
        }
        return redirect()->route('home');
    }
}

resources/views/customer_project/create.blade.php
@extends('layouts.master')

@push('css')
    
@endpush

@section('content')

<div class="app-title">
    <div>
        <h1><i class="fa fa-tasks"></i> Add Project</h1>
    </div>
    <div>
        <a href="{{ route('project.index') }}" class="btn btn-dark">
            <i class="fa fa-arrow-left"></i> Back
        </a>
    </div>
</div>
  
<div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="tile">
        <div class="tile-body">
          
            <form action="{{ route('project.store') }}" method="post">
                @csrf

                <div class="form-group row">
                    <label class="col-md-3" for="customer">Customer <span class="text-danger">*</span> </label>
                    <div class="col-md-9">
                        <select name="customer" id="customer" class="form-control">
                            <option value="" hidden>--- Select Customer ---</option>
                            @foreach ($customers as $customer)
                                <option value="{{ $customer->id }}" {{ old('customer') == $customer->id ? 'selected' : '' }}>
                                    {{ $customer->company_name }}
                                </option>
                            @endforeach
                        </select>
                        @error('customer')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-3" for="project_name">Project Name <span class="text-danger">*</span> </label>
                    <div class="col-md-9">
                        <input type="text" name="project_name" id="project_name" value="{{ old('project_name') }}" class="form-control">
                        @error('project_name')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-3" for="project_description">Description </label>
                    <div class="col-md-9">
                        <textarea name="project_description" id="project_description" class="form-control">{{ old('project_description') }}</textarea>
                        @error('project_description')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-9 offset-md-3">
                        <input type="submit" value="Submit" class="btn btn-info">
                    </div>
                </div>

            </form>

        </div>
      </div>
    </div>
  </div>

@endsection

@push('js')

@endpush

resources/views/customer_project/edit.blade.php
@extends('layouts.master')

@push('css')
    
@endpush

@section('content')

<div class="app-title">
    <div>
        <h1><i class="fa fa-tasks"></i> Edit Project</h1>
    </div>
    <div>
        <a href="{{ route('project.index') }}" class="btn btn-dark">
            <i class="fa fa-arrow-left"></i> Back
        </a>
    </div>
</div>
  
<div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="tile">
        <div class="tile-body">
          
            <form action="{{ route('project.update', $project->id) }}" method="post">
                @csrf
                @method('PUT')

                <div class="form-group row">
                    <label class="col-md-3" for="customer">Customer <span class="text-danger">*</span> </label>
                    <div class="col-md-9">
                        <select name="customer" id="customer" class="form-control">
                            <option value="" hidden>--- Select Customer ---</option>
                            @foreach ($customers as $customer)
                                <option value="{{ $customer->id }}" {{ $project->customer_id == $customer->id ? 'selected' : '' }}>
                                    {{ $customer->company_name }}
                                </option>
                            @endforeach
                        </select>
                        @error('customer')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-3" for="project_name">Project Name <span class="text-danger">*</span> </label>
                    <div class="col-md-9">
                        <input type="text" name="project_name" id="project_name" value="{{ $project->project_name }}" class="form-control">
                        @error('project_name')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-3" for="project_description">Description </label>
                    <div class="col-md-9">
                        <textarea name="project_description" id="project_description" class="form-control">{{ $project->project_description }}</textarea>
                        @error('project_description')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-9 offset-md-3">
                        <input type="submit" value="Update" class="btn btn-info">
                    </div>
                </div>

            </form>

        </div>
      </div>
    </div>
  </div>

@endsection

@push('js')

@endpush

resources/views/customer_project/index.blade.php
@extends('layouts.master')

@push('css')
    
@endpush

@section('content')

<div class="app-title">
    <div>
        <h1><i class="fa fa-tasks"></i> Customer Projects</h1>
    </div>
    <div>
        <a href="{{ route('project.create') }}" class="btn btn-primary">
            <i class="fa fa-plus"></i> Add New Project
        </a>
    </div>
</div>

@if (session('message'))
    {!! session('message') !!}
@endif
  
<div class="row">
    <div class="col-md-12">
      <div class="tile">
        <div class="tile-body">
          <div class="table-responsive">
            <table class="table table-hover table-bordered" id="sampleTable">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Customer</th>
                  <th>Project Name</th>
                  <th>Description</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($customer_projects as $key => $customer_project)
                  <tr>
                    <td>{{ ++$key }}</td>
                    <td>
                        {{ $customer_project->customer->company_name }}
                        <small class="d-block">{{ $customer_project->customer->phone }}</small>
                    </td>
                    <td>{{ $customer_project->project_name }}</td>
                    <td>{{ $customer_project->project_description ?? '---' }}</td>
                    <td>
                        <div class="btn-group">
                            <a href="{{ route('project.edit', $customer_project->id) }}" class="btn btn-info btn-sm">
                                <i class="fa fa-edit"></i>
                            </a>
                            @can('admin-only', Auth::user())
                            <form action="{{ route('project.destroy', $customer_project->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="delete_button btn btn-danger btn-sm"> 
                                    <i class="fa fa-trash"></i> 
                                </button>
                            </form>
                            @endcan
                        </div>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

@endsection

@push('js')
<script type="text/javascript" src="{{ asset('assets/') }}/js/plugins/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="{{ asset('assets/') }}/js/plugins/dataTables.bootstrap.min.js"></script>
<script type="text/javascript" src="{{ asset('assets/') }}/js/sweetalert2@9.js"></script>
<script type="text/javascript">

    $('#sampleTable').DataTable();

    $(document).on('click', '.delete_button', function (e) {
        e.preventDefault();
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value) {
                $(this).closest('form').submit();
            }
        });
    });
</script>
@endpush