routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'AuthController@showLoginForm')->name('login');
Route::post('/login', 'AuthController@loginProcess')->name('login.process');
Route::post('/logout', 'AuthController@logoutProcess')->name('logout.process');

Route::group(['middleware' => 'auth'], function() {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/employee', 'EmployeeController')->middleware('admin');
    
    // Route::view('/p', 'employee.permission');
    // Route::get('/pdf', function () {
    //     $pdf = PDF::loadView('attendance.pdf', []);
	//     return $pdf->stream('document.pdf');
    // });

    Route::get('/attendance', 'AttendanceController@getAttendances')->name('attendance');
    Route::post('/attendance/receive', 'AttendanceController@attendanceStore')->name('attendance.receive');
    Route::get('/attendance/search', 'AttendanceController@attendanceSearch')->name('attendance.search');

    Route::get('/profile', 'EmployeeController@profile')->name('employee.profile');
    Route::post('/password-reset', 'EmployeeController@resetPassword')->name('password.new');
    Route::post('/image/change', 'EmployeeController@imageChange')->name('employee.image.change');

    Route::resource('/customer', 'CustomerController');
    Route::get('/customer/{id}/approve', 'CustomerController@approve')->name('customer.approve');

    Route::resource('/project', 'CustomerProjectController');

    Route::get('/setup/types', 'CustomerTypeController@index')->name('customer.types');
    Route::post('/setup/type/store', 'CustomerTypeController@store')->name('customer.type.store');
    Route::get('/setup/type/{id}/edit', 'CustomerTypeController@edit')->name('customer.type.edit');
    Route::post('/setup/type/update', 'CustomerTypeController@update')->name('customer.type.update');
    Route::delete('/setup/type/{id}/delete', 'CustomerTypeController@destroy')->name('customer.type.delete');

    Route::resource('/product', 'ProductController');

    Route::get('/visits', 'VisitController@index')->name('visits');
    Route::get('/visit/create', 'VisitController@create')->name('visit.create');
    Route::post('/visit/store', 'VisitController@store')->name('visit.store');
    Route::get('/visit/{id}/show', 'VisitController@show')->name('visit.show');
    Route::get('/visit/{id}/edit', 'VisitController@edit')->name('visit.edit');
    Route::put('/visit/update', 'VisitController@update')->name('visit.update');
    Route::delete('/visit/{id}/destroy', 'VisitController@destroy')->name('visit.destroy');

    Route::get('/orders/{with_details?}', 'OrderController@index')->name('orders');
    Route::get('/order/create', 'OrderController@create')->name('order.create');
    Route::post('/order/confirm', 'OrderController@confirmOrder')->name('order.confirm');
    Route::get('/order/{id}/invoice', 'OrderController@invoice')->name('order.invoice');

    Route::get('/order/{id}/show', 'OrderController@show')->name('order.show');
    Route::get('/order/{id}/edit', 'OrderController@edit')->name('order.edit');
    Route::post('/order/update', 'OrderController@update')->name('order.update');
    Route::post('/order/delete', 'OrderController@destroy')->name('order.destroy');

    Route::get('/order/{id}/delivery', 'OrderDeliveryController@deliveryForm')->name('order.delivery');
    Route::post('/order/delivery', 'OrderDeliveryController@deliveryProcess')->name('order.delivery.process');

    // oid = order id, bid = delivery batch id
    Route::get('/order/{oid}/{bid}/chalan', 'OrderDeliveryController@chalan')->name('order.delivery.chalan');

    Route::get('/pending-orders', 'OrderController@pending')->name('order.pending');
    Route::get('/archive-orders', 'OrderController@archive')->name('order.archive');

    Route::group(['middleware'=>'admin'], function() {

        Route::resource('/setup/post', 'EmployeePostController')->except('show');
        Route::resource('/setup/department', 'EmployeeDepartmentController')->except('show');
        Route::resource('/setup/company', 'CompanyController')->except('show');
        
        Route::get('/settings', 'SettingsController@otherSettings')->name('settings');
        Route::post('/settings/update', 'SettingsController@settingsUpdate')->name('settings.update');

        Route::get('/setup/transports', 'TransportModeController@index')->name('transports');
        Route::post('/setup/transport/store', 'TransportModeController@store')->name('transport.store');
        Route::get('/setup/transport/{id}/edit', 'TransportModeController@edit')->name('transport.edit');
        Route::post('/setup/transport/update', 'TransportModeController@update')->name('transport.update');
        Route::delete('/setup/transport/{id}/delete', 'TransportModeController@destroy')->name('transport.delete');

        Route::get('/setup/job-types', 'JobTypeController@index')->name('job.types');
        Route::post('/setup/job-type/store', 'JobTypeController@store')->name('job.type.store');
        Route::get('/setup/job-type/{id}/edit', 'JobTypeController@edit')->name('job.type.edit');
        Route::post('/setup/job-type/update', 'JobTypeController@update')->name('job.type.update');
        Route::delete('/setup/job-type/{id}/delete', 'JobTypeController@destroy')->name('job.type.delete');
    });

    Route::get('/report/visit-report', 'ReportController@visitReport')->name('report.visit-report');
    Route::get('/report/visit', 'ReportController@visitReportProcess')->name('report.visit');

    Route::get('/report/order-report', 'ReportController@orderReport')->name('report.order-report');
    Route::post('/report/order', 'ReportController@orderReportProcess')->name('report.order');

});

app/Models/CustomerType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CustomerType extends Model
{
    protected $fillable = ['type', 'isDelete'];
}

app/Http/Controllers/Api/CustomerController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Customer;
use App\Models\Product;
use App\Models\CustomerType;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class CustomerController extends Controller
{
    public function getCustomerTypes() {
        $customer_types = CustomerType::where('isDelete', 0)->get();
        if ($customer_types->count() > 0) {
            return response()->json([
                'success' => true,
                'data' => $customer_types
            ]);
        }
        return response()->json([
            'success' => false,
            'message' => 'Customer types not found'
        ]);
    }

    public function getCustomers() {
        // if ($this->apiIsAdmin()) {
        //     $customers = Customer::where('isDelete', 0)->get();
        // } else {
        //     $customers = Customer::with('projects')
        //                 ->where('isDelete', 0)
        //                 ->where('saved_by', app('currentUserId'))
        //                 ->get();
        // }
        $customers = Customer::with('projects')->where('isDelete', 0)->get();
        $products = Product::where('isDelete', 0)->get();
        if ($customers->count() > 0) {
            return response()->json([
                'success' => true,
                'data' => $customers,
                'products' => $products
            ], 200);
        }
        return response()->json([
            'success' => false,
            'message' => 'Customers not found'
        ], 200);
    }

    public function storeCustomerInfo(Request $request) {
        
        $validator = Validator::make($request->all(), [
            'company_name' => 'required',
            'contact_person' => 'required',
            'phone' => 'required|min:11|max:15',
            'address' => 'required',
            'customer_type_id' => 'required',
            'marketing_officer_id' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'message' => $validator->errors()
            ], 200);
        }

        try {
            Customer::create([
                'customer_id' => $this->generateCustomerId(),
                'company_name' => $request->company_name,
                'contact_person' => $request->contact_person,
                'address' => $request->address,
                'phone' => $request->phone,
                'customer_type_id' => $request->customer_type_id,
                'marketing_officer_id' => $request->marketing_officer_id,
                'saved_by' => app('currentUserId')
            ]);
            
            return response()->json([
                'success' => true,
                'message' => 'Customer info save successfully.'
            ], 201);

        } catch (\Exception $e) {
            
            return response()->json([
                'success' => false,
                'message' => $e->getMessage()
            ], 200);
        }
    }

    public function getCustomerInfo($id) {

        $customer = Customer::with('projects')->findOrFail($id);
        $customer->saved_by = $customer->savedBy;
        $customer->updated_by = $customer->updatedBy;

        if ($customer->count() > 0) {
            return response()->json([
                'success' => true,
                'data' => $customer
            ], 200);
        }
        return response()->json([
            'success' => false,
            'message' => 'Customer not found'
        ], 404);
    }

    public function updateCustomerInfo(Request $request) {

        $validator = Validator::make($request->all(), [
            'customer_id' => 'required',
            'company_name' => 'required',
            'contact_person' => 'required',
            'phone' => 'required|min:11|max:15',
            'address' => 'required',
            'customer_type_id' => 'required',
            'marketing_officer_id' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json([
                'success' => false,
                'message' => $validator->errors()
            ], 422);
        }

        try {
            $customer = Customer::findOrFail($request->customer_id);
            $customer->company_name = $request->company_name;
            $customer->contact_person = $request->contact_person;
            $customer->phone = $request->phone;
            $customer->address = $request->address;
            $customer->customer_type_id = $request->customer_type_id;
            $customer->marketing_officer_id = $request->marketing_officer_id;
            $customer->updated_by = app('currentUserId');
            $customer->save();

            return response()->json([
                'success' => true,
                'message' => 'Customer info update successfully.'
            ], 200);

        } catch (\Exception $e) {

            return response()->json([
                'success' => false,
                'message' => $e->getMessage()
            ], 422);
        }
    }

    public function deleteCustomerInfo($id) {

        try {

            $customer = Customer::findOrFail($id);
            $customer->isDelete = 1;
            $customer->save();

            return response()->json([
                'success' => true,
                'message' => 'Customer info delete successfully.'
            ], 200);

        } catch (\Exception $e) {

            return response()->json([
                'success' => false,
                'message' => $e->getMessage()
            ], 422);
        }
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Models\Customer;
use App\Models\CustomerType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class CustomerController extends Controller
{
    public function index() {
        if ($this->isAdmin()) {
            $customers = Customer::where('isDelete', 0)->latest()->get();
        } else {
            $customers = Customer::where('isDelete', 0)->where('saved_by', Auth::id())->latest()->get();
        }
        return view('customer.index', compact('customers'));
    }

    public function create() {
        return view('customer.create', [
            'new_id' => $this->generateCustomerId(),
            'customer_types' => CustomerType::where('isDelete', 0)->get(),
            'employees' => User::where('isAdmin', 0)->where('isDelete', 0)->latest()->get()
        ]);
    }

    public function store(Request $request) {
        $this->validateCustomerInfo($request);

        $newCustomer = [
            'customer_id' => $this->generateCustomerId(),
            'company_name' => $request->company_name,
            'contact_person' => $request->contact_person,
            'area' => $request->area,
            'address' => $request->address,
            'phone' => $request->phone,
            'customer_type_id' => $request->customer_type,
            'saved_by' => Auth::user()->id
        ];

        if ($this->isAdmin()) {
            $newCustomer['isApproved'] = 1;
            $newCustomer['marketing_officer_id'] = $request->marketing_officer;
        } else {
            $newCustomer['marketing_officer_id'] = Auth::user()->id;
        }

        try {
            Customer::create($newCustomer);
            $this->message('success', 'Customer info save successfully.');
        } catch (\Exception $e) {
            $this->message('error', $e->getMessage());
        }
        return redirect()->route('customer.index');
    }

    private function validateCustomerInfo($request) {
        $request->validate([
            'company_name' => 'required',
            'contact_person' => 'required',
            'phone' => 'required|min:11|max:15',
            'address' => 'required',
            'customer_type' => 'required'
        ]);

        if ($this->isAdmin()) {
            $request->validate([
                'marketing_officer' => 'required'
            ]);
        }
    }

    public function show($id) {
        $customer = Customer::with('projects', 'customer_type', 'marketing_officer')->findOrFail($id);
        $customer->saved_by = $customer->savedBy;
        $customer->updated_by = $customer->updatedBy;
        $customer->customer_type_name = $customer->customer_type->type;
        $customer->marketing_officer = $customer->marketing_officer; 
        return response()->json($customer);
    }

    public function edit($id) {
        $customer = Customer::findOrFail($id);
        $customer_types = CustomerType::where('isDelete', 0)->get();
        $employees = User::where('isAdmin', 0)->where('isDelete', 0)->latest()->get();
        if ($this->isOwn($customer->saved_by) || $this->isAdmin()) {
            return view('customer.edit', compact('customer', 'customer_types', 'employees'));
        }
        abort(403);
    }

    public function update(Request $request, $id) {
        $this->validateCustomerInfo($request);
        $customer = Customer::findOrFail($id);
        if ($this->isOwn($customer->saved_by) || $this->isAdmin()) {
            try {
                $customer->company_name = $request->company_name;
                $customer->contact_person = $request->contact_person;
                $customer->phone = $request->phone;
                $customer->area = $request->area;
                $customer->address = $request->address;
                $customer->customer_type_id = $request->customer_type;
                if ($this->isAdmin()) {
                    $customer->marketing_officer_id = $request->marketing_officer;
                } else {
                    $customer->marketing_officer_id = Auth::user()->id;
                }
                $customer->updated_by = Auth::user()->id;
                $customer->save();
    
                $this->message('success', 'Customer info update successfully.');
            } catch (\Exception $e) {
                $this->message('error', $e->getMessage());
            }
            return redirect()->route('customer.index');
        }
        abort(403);
    }

    public function destroy($id) {
        if (Gate::allows('admin-only', Auth::user())) {
            try {
                $customer = Customer::findOrFail($id);
                $customer->isDelete = 1;
                $customer->save();
    
                $this->message('success', 'Customer info delete successfully');
            } catch (\Exception $e) {
                $this->message('error', $e->getMessage());
            }
            return redirect()->route('customer.index');
        }
        return redirect()->route('home');
    }

    public function approve($id) {
        if (Gate::allows('admin-only', Auth::user())) {
            try {
                $customer = Customer::findOrFail($id);
                $customer->isApproved = 1;
                $customer->save();
    
                $this->message('success', 'Customer successfully approved');
            } catch (\Exception $e) {
                $this->message('error', $e->getMessage());
            }
            return redirect()->route('customer.index');
        }
        return redirect()->route('home');
    }
}

resources/views/customer/create.blade.php
@extends('layouts.master')

@push('css')
    
@endpush

@section('content')

<div class="app-title">
    <div>
        <h1><i class="fa fa-user-plus"></i> Add Customer</h1>
    </div>
    <div>
        <a href="{{ route('customer.index') }}" class="btn btn-dark">
            <i class="fa fa-arrow-left"></i> Back
        </a>
    </div>
</div>
  
<div class="row">
    <div class="col-md-12">
      <div class="tile">
        <div class="tile-body">

            <form action="{{ route('customer.store') }}" method="post">
                @csrf

                <div class="row">

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Customer ID</label>
                            <input type="text" value="{{ $new_id }}" readonly class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="company_name">Company Name <span class="text-danger">*</span> </label>
                            <input type="text" name="company_name" id="company_name" value="{{ old('company_name') }}" class="form-control">
                            @error('company_name')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="contact_person">Contact Person <span class="text-danger">*</span> </label>
                            <input type="text" name="contact_person" id="contact_person" value="{{ old('contact_person') }}" class="form-control">
                            @error('contact_person')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="phone">Phone <span class="text-danger">*</span> </label>
                            <input type="text" name="phone" id="phone" value="{{ old('phone') }}" class="form-control">
                            @error('phone')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="area">Area </label>
                            <input type="text" name="area" id="area" value="{{ old('area') }}" class="form-control">
                            @error('area')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="address">Address <span class="text-danger">*</span> </label>
                            <textarea name="address" id="address" class="form-control">{{ old('address') }}</textarea>
                            @error('address')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="customer_type">Customer Type <span class="text-danger">*</span> </label>
                            <select name="customer_type" id="customer_type" class="form-control">
                                <option value="">-- Select Customer Type --</option>
                                @foreach ($customer_types as $c_type)
                                    <option value="{{ $c_type->id }}" {{ old('customer_type') == $c_type->id ? 'selected' : '' }}>{{ $c_type->type }}</option>
                                @endforeach
                            </select>
                            @error('customer_type')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>

                        @can('admin-only', Auth::user())
                            <div class="form-group">
                                <label for="marketing_officer">Marketing Officer <span class="text-danger">*</span> </label>
                                <select name="marketing_officer" id="marketing_officer" class="form-control">
                                    <option value="">-- Select Marketing Officer --</option>
                                    @foreach ($employees as $employee)
                                    <option value="{{ $employee->id }}" {{ old('marketing_officer') == $employee->id ? 'selected' : '' }}>{{ $employee->employee_name }}</option>
                                    @endforeach
                                </select>
                                @error('marketing_officer')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        @endcan
                        
                    </div>
                </div>

                <div class="col-md-6 offset-md-3">
                    <input type="submit" value="Submit" class="btn btn-info btn-block">
                </div>

            </form>

        </div>
      </div>
    </div>
  </div>

@endsection

@push('js')
  
@endpush

resources/views/customer/index.blade.php
@extends('layouts.master')

@push('css')
    
@endpush

@section('content')

<div class="app-title">
    <div>
        <h1><i class="fa fa-users"></i> Customers</h1>
    </div>
    <div>
        <a href="{{ route('customer.create') }}" class="btn btn-primary">
            <i class="fa fa-user-plus"></i> Add New Customer
        </a>
    </div>
</div>

@if (session('message'))
    {!! session('message') !!}
@endif
  
<div class="row">
    <div class="col-md-12">
      <div class="tile">
        <div class="tile-body">
          <div class="table-responsive">
            <table class="table table-hover table-bordered" id="sampleTable">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>
                  <th>Customer Name</th>
                  <th>Contact Person</th>
                  <th>Phone</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($customers as $key => $customer)
                  <tr>
                    <td>{{ ++$key }}</td>
                    <td>{{ $customer->customer_id }}</td>
                    <td>{{ $customer->company_name }}</td>
                    <td>{{ $customer->contact_person }}</td>
                    <td>{{ $customer->phone }}</td>
                    <td>
                        @if ((Auth::user()->isAdmin == 1) && ($customer->isApproved == 0))
                            <a href="{{ route('customer.approve', $customer->id) }}" class="btn btn-warning btn-sm">Approve</a>
                        @elseif ($customer->isApproved == 0)
                            <span class="badge badge-warning">Pending</span>
                        @elseif ($customer->isApproved == 1)
                            <span class="badge badge-success">Approved</span>
                        @endif
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" data-id="{{ $customer->id }}" class="show-modal btn btn-dark btn-sm">
                                <i class="fa fa-eye"></i>
                            </button>
                            <a href="{{ route('customer.edit', $customer->id) }}" class="btn btn-info btn-sm">
                                <i class="fa fa-edit"></i>
                            </a>
                            @can('admin-only', Auth::user())
                            <form action="{{ route('customer.destroy', $customer->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="delete_button btn btn-danger btn-sm"> 
                                    <i class="fa fa-trash"></i> 
                                </button>
                            </form>
                            @endcan
                        </div>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
          <div class="modal-header p-3">
            <h5 class="modal-title" id="exampleModalLabel">Customer Information</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          
          <div class="my-3 ml-4 mr-4">
            <table class="table table-borderless _table">
                <tr>
                    <th>Customer ID</th>
                    <th>:</th>
                    <td id="c_id"></td>
                </tr>
                <tr>
                    <th>Company Name</th>
                    <th>:</th>
                    <td id="c_customer_name"></td>
                </tr>
                <tr>
                    <th>Contact Person</th>
                    <th>:</th>
                    <td id="c_contact_person"></td>
                </tr>
                <tr>
                    <th>Phone</th>
                    <th>:</th>
                    <td id="c_phone"></td>
                </tr>
                <tr>
                    <th>Area</th>
                    <th>:</th>
                    <td id="c_area"></td>
                </tr>
                <tr>
                    <th>Address</th>
                    <th>:</th>
                    <td id="c_address"></td>
                </tr>
                <tr>
                    <th>Customer Type</th>
                    <th>:</th>
                    <td id="c_customer_type"></td>
                </tr>
                <tr>
                    <th>Marketing Officer</th>
                    <th>:</th>
                    <td id="c_marketing_officer"></td>
                </tr>
                <tr>
                    <th>Saved By</th>
                    <th>:</th>
                    <td id="c_sb"></td>
                </tr>
                <tr>
                    <th>Updated By</th>
                    <th>:</th>
                    <td id="c_ub"></td>
                </tr>
            </table>
          </div>
      </div>
    </div>
  </div>

@endsection

@push('js')
<script type="text/javascript" src="{{ asset('assets/') }}/js/plugins/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="{{ asset('assets/') }}/js/plugins/dataTables.bootstrap.min.js"></script>
<script type="text/javascript" src="{{ asset('assets/') }}/js/sweetalert2@9.js"></script>
<script type="text/javascript">

    $('#sampleTable').DataTable();

    $(document).on('click', '.show-modal', function() {
        var this_id = $(this).data('id');
        if ('' != this_id) {
            var route = '{{ route('customer.show', ':id') }}';
            var _url = route.replace(':id', this_id);
            $.ajax({
                url: _url,
                method: 'GET',
                success: function(response) {
                    $('#c_id').text(response.customer_id);
                    $('#c_customer_name').text(response.company_name);
                    $('#c_contact_person').text(response.contact_person);
                    $('#c_phone').text(response.phone);
                    $('#c_area').text(response.area);
                    $('#c_address').text(response.address);
                    $('#c_customer_type').text(response.customer_type_name);
                    $('#c_marketing_officer').text(response.marketing_officer.employee_name);
                    if (response.saved_by.username != null) {
                        $('#c_sb').text(response.saved_by.username);
                    } else {
                        $('#c_sb').text(response.saved_by.employee_name);
                    }
                    if (response.updated_by != null) {
                        if (response.updated_by.username != null) {
                            $('#c_ub').text(response.updated_by.username);
                        } else {
                            $('#c_ub').text(response.updated_by.employee_name);
                        }
                    }

                    $('._table').children('tbody').children('tr').children('td').each(function() {
                        if ($(this).text() == '') {
                            $(this).closest('tr').remove();
                        }
                    });

                    $('.bd-example-modal-lg').modal('show');
                }
            });
        }
    });

    $(document).on('click', '.delete_button', function (e) {
        e.preventDefault();
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value) {
                $(this).closest('form').submit();
            }
        });
    });
</script>
@endpush