routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'AuthController@showLoginForm')->name('login');
Route::post('/login', 'AuthController@loginProcess')->name('login.process');
Route::post('/logout', 'AuthController@logoutProcess')->name('logout.process');

Route::group(['middleware' => 'auth'], function() {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/employee', 'EmployeeController')->middleware('admin');
    
    // Route::view('/p', 'employee.permission');
    // Route::get('/pdf', function () {
    //     $pdf = PDF::loadView('attendance.pdf', []);
	//     return $pdf->stream('document.pdf');
    // });

    Route::get('/attendance', 'AttendanceController@getAttendances')->name('attendance');
    Route::post('/attendance/receive', 'AttendanceController@attendanceStore')->name('attendance.receive');
    Route::get('/attendance/search', 'AttendanceController@attendanceSearch')->name('attendance.search');

    Route::get('/profile', 'EmployeeController@profile')->name('employee.profile');
    Route::post('/password-reset', 'EmployeeController@resetPassword')->name('password.new');
    Route::post('/image/change', 'EmployeeController@imageChange')->name('employee.image.change');

    Route::resource('/customer', 'CustomerController');
    Route::get('/customer/{id}/approve', 'CustomerController@approve')->name('customer.approve');

    Route::resource('/project', 'CustomerProjectController');

    Route::get('/setup/types', 'CustomerTypeController@index')->name('customer.types');
    Route::post('/setup/type/store', 'CustomerTypeController@store')->name('customer.type.store');
    Route::get('/setup/type/{id}/edit', 'CustomerTypeController@edit')->name('customer.type.edit');
    Route::post('/setup/type/update', 'CustomerTypeController@update')->name('customer.type.update');
    Route::delete('/setup/type/{id}/delete', 'CustomerTypeController@destroy')->name('customer.type.delete');

    Route::resource('/product', 'ProductController');

    Route::get('/visits', 'VisitController@index')->name('visits');
    Route::get('/visit/create', 'VisitController@create')->name('visit.create');
    Route::post('/visit/store', 'VisitController@store')->name('visit.store');
    Route::get('/visit/{id}/show', 'VisitController@show')->name('visit.show');
    Route::get('/visit/{id}/edit', 'VisitController@edit')->name('visit.edit');
    Route::put('/visit/update', 'VisitController@update')->name('visit.update');
    Route::delete('/visit/{id}/destroy', 'VisitController@destroy')->name('visit.destroy');

    Route::get('/orders/{with_details?}', 'OrderController@index')->name('orders');
    Route::get('/order/create', 'OrderController@create')->name('order.create');
    Route::post('/order/confirm', 'OrderController@confirmOrder')->name('order.confirm');
    Route::get('/order/{id}/invoice', 'OrderController@invoice')->name('order.invoice');

    Route::get('/order/{id}/show', 'OrderController@show')->name('order.show');
    Route::get('/order/{id}/edit', 'OrderController@edit')->name('order.edit');
    Route::post('/order/update', 'OrderController@update')->name('order.update');
    Route::post('/order/delete', 'OrderController@destroy')->name('order.destroy');

    Route::get('/order/{id}/delivery', 'OrderDeliveryController@deliveryForm')->name('order.delivery');
    Route::post('/order/delivery', 'OrderDeliveryController@deliveryProcess')->name('order.delivery.process');

    // oid = order id, bid = delivery batch id
    Route::get('/order/{oid}/{bid}/chalan', 'OrderDeliveryController@chalan')->name('order.delivery.chalan');

    Route::get('/pending-orders', 'OrderController@pending')->name('order.pending');
    Route::get('/archive-orders', 'OrderController@archive')->name('order.archive');

    Route::group(['middleware'=>'admin'], function() {

        Route::resource('/setup/post', 'EmployeePostController')->except('show');
        Route::resource('/setup/department', 'EmployeeDepartmentController')->except('show');
        Route::resource('/setup/company', 'CompanyController')->except('show');
        
        Route::get('/settings', 'SettingsController@otherSettings')->name('settings');
        Route::post('/settings/update', 'SettingsController@settingsUpdate')->name('settings.update');

        Route::get('/setup/transports', 'TransportModeController@index')->name('transports');
        Route::post('/setup/transport/store', 'TransportModeController@store')->name('transport.store');
        Route::get('/setup/transport/{id}/edit', 'TransportModeController@edit')->name('transport.edit');
        Route::post('/setup/transport/update', 'TransportModeController@update')->name('transport.update');
        Route::delete('/setup/transport/{id}/delete', 'TransportModeController@destroy')->name('transport.delete');

        Route::get('/setup/job-types', 'JobTypeController@index')->name('job.types');
        Route::post('/setup/job-type/store', 'JobTypeController@store')->name('job.type.store');
        Route::get('/setup/job-type/{id}/edit', 'JobTypeController@edit')->name('job.type.edit');
        Route::post('/setup/job-type/update', 'JobTypeController@update')->name('job.type.update');
        Route::delete('/setup/job-type/{id}/delete', 'JobTypeController@destroy')->name('job.type.delete');
    });

    Route::get('/report/visit-report', 'ReportController@visitReport')->name('report.visit-report');
    Route::get('/report/visit', 'ReportController@visitReportProcess')->name('report.visit');

    Route::get('/report/order-report', 'ReportController@orderReport')->name('report.order-report');
    Route::post('/report/order', 'ReportController@orderReportProcess')->name('report.order');

});

resources/views/partial/header.blade.php
<header class="app-header">
  <a class="app-header__logo" href="{{ route('home') }}">{{ $_settings->company_name }}</a>
  <!-- Sidebar toggle button-->
  <a class="app-sidebar__toggle" href="javascript:" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
  <!-- Navbar Right Menu-->
  <ul class="app-nav">
    <li>
      <div class="timer">
        <i class="fa fa-clock-o"></i> {{ date('l') }}, {{ date('d F Y') }}, <span id="clock"></span>
      </div>
    </li>
    <!-- User Menu-->
    <li class="dropdown"><a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
      <ul class="dropdown-menu settings-menu dropdown-menu-right">
        <li>
          <a class="dropdown-item" href="{{ route('employee.profile') }}">
            <i class="fa fa-user fa-lg"></i> Profile
          </a>
        </li>
        <li>
          <a class="dropdown-item" href="{{ route('logout.process') }}"
              onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
              <i class="fa fa-sign-out fa-lg"></i> {{ __('Logout') }}
          </a>

          <form id="logout-form" action="{{ route('logout.process') }}" method="POST" style="display: none;">
              @csrf
          </form>
        </li>
      </ul>
    </li>
  </ul>
</header>

resources/views/partial/sidebar.blade.php
<div class="app-sidebar__overlay" data-toggle="sidebar"></div>
    <aside class="app-sidebar">
      <div class="app-sidebar__user">
        @if (Auth::user()->employee_picture)
        <img class="app-sidebar__user-avatar" src="{{ asset(Auth::user()->employee_picture) }}" height="50" alt="User Image">
        @else
        <img class="app-sidebar__user-avatar" src="{{ asset('assets/images/male-avatar.jpg') }}" height="50" alt="User Image">
        @endif
        <div>
          <p class="app-sidebar__user-name">{{ Auth::user()->employee_name ?? ucfirst(Auth::user()->username) }}</p>
          <p class="app-sidebar__user-designation">{{ Auth::user()->employee_post->post_name ?? '' }}</p>
        </div>
      </div>
      <ul class="app-menu">
        <li>
          <a class="app-menu__item {{ request()->is('home*') ? 'active' : '' }}" href="{{ route('home') }}">
            <i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Dashboard</span>
          </a>
        </li>
        <li>
          <a class="app-menu__item {{ request()->is('attendance*') ? 'active' : '' }}" href="{{ route('attendance') }}">
            <i class="app-menu__icon fa fa-clock-o"></i><span class="app-menu__label">Attendance</span>
          </a>
        </li>
        <li class="treeview {{ request()->is('*order*') ? 'is-expanded' : '' }}">
          <a class="app-menu__item" href="javascript:" data-toggle="treeview">
            <i class="app-menu__icon fa fa-shopping-cart"></i>
            <span class="app-menu__label">Order</span>
            <i class="treeview-indicator fa fa-angle-right"></i>
          </a>
          <ul class="treeview-menu">
            <li>
              <a class="app-menu__item {{ request()->is('order*') ? 'active' : '' }}" href="{{ route('orders') }}">
                <i class="app-menu__icon fa fa-shopping-cart"></i><span class="app-menu__label">Orders</span>
              </a>
            </li>
            <li>
              <a class="app-menu__item {{ request()->is('pending-orders') ? 'active' : '' }}" href="{{ route('order.pending') }}">
                <i class="app-menu__icon fa fa-clock-o"></i><span class="app-menu__label">Pending Order</span>
              </a>
            </li>
            <li>
              <a class="app-menu__item {{ request()->is('archive-orders') ? 'active' : '' }}" href="{{ route('order.archive') }}">
                <i class="app-menu__icon fa fa-archive"></i><span class="app-menu__label">Archive Order</span>
              </a>
            </li>
          </ul>
        </li>
        @can('admin-only', Auth::user())
        <li>
          <a class="app-menu__item {{ request()->is('employee*') ? 'active' : '' }}" href="{{ route('employee.index') }}">
            <i class="app-menu__icon fa fa-users"></i><span class="app-menu__label">Employee</span>
          </a>
        </li>
        @endcan
        <li>
          <a class="app-menu__item {{ request()->is('visit*') ? 'active' : '' }}" href="{{ route('visits') }}">
            <i class="app-menu__icon fa fa-car"></i><span class="app-menu__label">Visit</span>
          </a>
        </li>
        <li>
          <a class="app-menu__item {{ request()->is('customer*') ? 'active' : '' }}" href="{{ route('customer.index') }}">
            <i class="app-menu__icon fa fa-users"></i><span class="app-menu__label">Customer</span>
          </a>
        </li>
        <li>
          <a class="app-menu__item {{ request()->is('project*') ? 'active' : '' }}" href="{{ route('project.index') }}">
            <i class="app-menu__icon fa fa-tasks"></i><span class="app-menu__label">Project</span>
          </a>
        </li>
        <li>
          <a class="app-menu__item {{ request()->is('product*') ? 'active' : '' }}" href="{{ route('product.index') }}">
            <i class="app-menu__icon fa fa-list"></i><span class="app-menu__label">Product</span>
          </a>
        </li>
        <li class="treeview">
          <a class="app-menu__item" href="javascript:" data-toggle="treeview">
            <i class="app-menu__icon fa fa-file"></i>
            <span class="app-menu__label">Report</span>
            <i class="treeview-indicator fa fa-angle-right"></i>
          </a>
          <ul class="treeview-menu">
            <li>
              <a href="{{ route('report.visit-report') }}" class="app-menu__item">
                  <i class="app-menu__icon fa fa-list"></i> Visit Report
              </a>
            </li>
            <li>
              <a href="{{ route('report.order-report') }}" class="app-menu__item">
                  <i class="app-menu__icon fa fa-list"></i> Order Report
              </a>
            </li>
          </ul>
        </li>
        @can('admin-only', Auth::user())
        <li class="treeview {{ request()->is('setup*') ? 'is-expanded' : '' }}">
          <a class="app-menu__item" href="javascript:" data-toggle="treeview">
            <i class="app-menu__icon fa fa-cog"></i>
            <span class="app-menu__label">Setup</span>
            <i class="treeview-indicator fa fa-angle-right"></i>
          </a>
          <ul class="treeview-menu">
            <li>
              <a href="{{ route('post.index') }}" class="app-menu__item {{ request()->is('setup/post*') ? 'active' : '' }}">
                  <i class="app-menu__icon fa fa-list"></i> Employee Post
              </a>
            </li>
            <li>
              <a href="{{ route('department.index') }}" class="app-menu__item {{ request()->is('setup/department*') ? 'active' : '' }}">
                  <i class="app-menu__icon fa fa-building-o"></i> Employee Department
              </a>
            </li>
            <li>
              <a href="{{ route('company.index') }}" class="app-menu__item {{ request()->is('setup/company*') ? 'active' : '' }}">
                  <i class="app-menu__icon fa fa-building-o"></i> Company
              </a>
            </li>
            <li>
              <a href="{{ route('customer.types') }}" class="app-menu__item {{ request()->is('setup/type*') ? 'active' : '' }}">
                  <i class="app-menu__icon fa fa-building-o"></i> Customer Type
              </a>
            </li>
            <li>
              <a href="{{ route('transports') }}" class="app-menu__item {{ request()->is('setup/transport*') ? 'active' : '' }}">
                  <i class="app-menu__icon fa fa-truck"></i> Transport
              </a>
            </li>
            <li>
              <a href="{{ route('job.types') }}" class="app-menu__item {{ request()->is('setup/job-type*') ? 'active' : '' }}">
                  <i class="app-menu__icon fa fa-tasks"></i> Job Type
              </a>
            </li>
          </ul>
        </li>
        <li>
          <a href="{{ route('settings') }}" class="app-menu__item {{ request()->is('settings') ? 'active' : '' }}">
              <i class="app-menu__icon fa fa-cog"></i><span class="app-menu__label">Setting</span>
          </a>
        </li>
        @endcan

        

        {{-- <li class="treeview {{ request()->is('employee*') ? 'is-expanded' : '' }}">
          <a class="app-menu__item" href="javascript:" data-toggle="treeview">
            <i class="app-menu__icon fa fa-user"></i>
            <span class="app-menu__label">Employee</span>
            <i class="treeview-indicator fa fa-angle-right"></i>
          </a>
          <ul class="treeview-menu">
            <li>
              <a href="" class="app-menu__item {{ request()->is('employee/create') ? 'active' : '' }}">
                  <i class="app-menu__icon fa fa-plus"></i> Add New
              </a>
            </li>
          </ul>
        </li> --}}

      </ul>
    </aside>