routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'AuthController@showLoginForm')->name('login');
Route::post('/login', 'AuthController@loginProcess')->name('login.process');
Route::post('/logout', 'AuthController@logoutProcess')->name('logout.process');

Route::group(['middleware' => 'auth'], function() {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/employee', 'EmployeeController')->middleware('admin');
    
    // Route::view('/p', 'employee.permission');
    // Route::get('/pdf', function () {
    //     $pdf = PDF::loadView('attendance.pdf', []);
	//     return $pdf->stream('document.pdf');
    // });

    Route::get('/attendance', 'AttendanceController@getAttendances')->name('attendance');
    Route::post('/attendance/receive', 'AttendanceController@attendanceStore')->name('attendance.receive');
    Route::get('/attendance/search', 'AttendanceController@attendanceSearch')->name('attendance.search');

    Route::get('/profile', 'EmployeeController@profile')->name('employee.profile');
    Route::post('/password-reset', 'EmployeeController@resetPassword')->name('password.new');
    Route::post('/image/change', 'EmployeeController@imageChange')->name('employee.image.change');

    Route::resource('/customer', 'CustomerController');
    Route::get('/customer/{id}/approve', 'CustomerController@approve')->name('customer.approve');

    Route::resource('/project', 'CustomerProjectController');

    Route::get('/setup/types', 'CustomerTypeController@index')->name('customer.types');
    Route::post('/setup/type/store', 'CustomerTypeController@store')->name('customer.type.store');
    Route::get('/setup/type/{id}/edit', 'CustomerTypeController@edit')->name('customer.type.edit');
    Route::post('/setup/type/update', 'CustomerTypeController@update')->name('customer.type.update');
    Route::delete('/setup/type/{id}/delete', 'CustomerTypeController@destroy')->name('customer.type.delete');

    Route::resource('/product', 'ProductController');

    Route::get('/visits', 'VisitController@index')->name('visits');
    Route::get('/visit/create', 'VisitController@create')->name('visit.create');
    Route::post('/visit/store', 'VisitController@store')->name('visit.store');
    Route::get('/visit/{id}/show', 'VisitController@show')->name('visit.show');
    Route::get('/visit/{id}/edit', 'VisitController@edit')->name('visit.edit');
    Route::put('/visit/update', 'VisitController@update')->name('visit.update');
    Route::delete('/visit/{id}/destroy', 'VisitController@destroy')->name('visit.destroy');

    Route::get('/orders/{with_details?}', 'OrderController@index')->name('orders');
    Route::get('/order/create', 'OrderController@create')->name('order.create');
    Route::post('/order/confirm', 'OrderController@confirmOrder')->name('order.confirm');
    Route::get('/order/{id}/invoice', 'OrderController@invoice')->name('order.invoice');

    Route::get('/order/{id}/show', 'OrderController@show')->name('order.show');
    Route::get('/order/{id}/edit', 'OrderController@edit')->name('order.edit');
    Route::post('/order/update', 'OrderController@update')->name('order.update');
    Route::post('/order/delete', 'OrderController@destroy')->name('order.destroy');

    Route::get('/order/{id}/delivery', 'OrderDeliveryController@deliveryForm')->name('order.delivery');
    Route::post('/order/delivery', 'OrderDeliveryController@deliveryProcess')->name('order.delivery.process');

    // oid = order id, bid = delivery batch id
    Route::get('/order/{oid}/{bid}/chalan', 'OrderDeliveryController@chalan')->name('order.delivery.chalan');

    Route::get('/pending-orders', 'OrderController@pending')->name('order.pending');
    Route::get('/archive-orders', 'OrderController@archive')->name('order.archive');

    Route::group(['middleware'=>'admin'], function() {

        Route::resource('/setup/post', 'EmployeePostController')->except('show');
        Route::resource('/setup/department', 'EmployeeDepartmentController')->except('show');
        Route::resource('/setup/company', 'CompanyController')->except('show');
        
        Route::get('/settings', 'SettingsController@otherSettings')->name('settings');
        Route::post('/settings/update', 'SettingsController@settingsUpdate')->name('settings.update');

        Route::get('/setup/transports', 'TransportModeController@index')->name('transports');
        Route::post('/setup/transport/store', 'TransportModeController@store')->name('transport.store');
        Route::get('/setup/transport/{id}/edit', 'TransportModeController@edit')->name('transport.edit');
        Route::post('/setup/transport/update', 'TransportModeController@update')->name('transport.update');
        Route::delete('/setup/transport/{id}/delete', 'TransportModeController@destroy')->name('transport.delete');

        Route::get('/setup/job-types', 'JobTypeController@index')->name('job.types');
        Route::post('/setup/job-type/store', 'JobTypeController@store')->name('job.type.store');
        Route::get('/setup/job-type/{id}/edit', 'JobTypeController@edit')->name('job.type.edit');
        Route::post('/setup/job-type/update', 'JobTypeController@update')->name('job.type.update');
        Route::delete('/setup/job-type/{id}/delete', 'JobTypeController@destroy')->name('job.type.delete');
    });

    Route::get('/report/visit-report', 'ReportController@visitReport')->name('report.visit-report');
    Route::get('/report/visit', 'ReportController@visitReportProcess')->name('report.visit');

    Route::get('/report/order-report', 'ReportController@orderReport')->name('report.order-report');
    Route::post('/report/order', 'ReportController@orderReportProcess')->name('report.order');

});

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    //
}

app/Http/Controllers/SettingsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Setting;
use Illuminate\Http\Request;

class SettingsController extends Controller
{
    public function otherSettings() {
        $settings = Setting::first();
        return view('setting.settings', compact('settings'));
    }

    public function settingsUpdate(Request $request) {
        $request->validate([
            'tax' => 'required|numeric',
            'company_name' => 'required',
            'phone_1' => 'required',
            'email_1' => 'required',
            'address' => 'required'
        ]);

        $settings = Setting::first();
        $settings->tax = $request->tax;
        $settings->company_name = $request->company_name;
        $settings->phone_1 = $request->phone_1;
        $settings->phone_2 = $request->phone_2;
        $settings->email_1 = $request->email_1;
        $settings->email_2 = $request->email_2;
        $settings->address = $request->address;
        $settings->save();

        $this->message('success', 'Settings successfully updated');
        return redirect()->back();
    }
}

resources/views/setting/department/create.blade.php
@extends('layouts.master')

@push('css')
    
@endpush

@section('content')

<div class="app-title">
    <div>
        <h1><i class="fa fa-user-plus"></i> Add Department</h1>
    </div>
    <div>
        <a href="{{ route('department.index') }}" class="btn btn-dark">
            <i class="fa fa-arrow-left"></i> Back
        </a>
    </div>
</div>
  
<div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="tile">
        <div class="tile-body">
          
            <form action="{{ route('department.store') }}" method="post">
                @csrf

                <div class="form-group row">
                    <label class="col-md-3" for="department_name">Department Name <span class="text-danger">*</span> </label>
                    <div class="col-md-9">
                        <input type="text" name="department_name" id="department_name" value="{{ old('department_name') }}" class="form-control">
                        @error('department_name')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-3" for="department_description">Description </label>
                    <div class="col-md-9">
                        <textarea name="department_description" id="department_description" class="form-control">{{ old('department_description') }}</textarea>
                        @error('department_description')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-9 offset-md-3">
                        <input type="submit" value="Submit" class="btn btn-info">
                    </div>
                </div>

            </form>

        </div>
      </div>
    </div>
  </div>

@endsection

@push('js')

@endpush

resources/views/setting/department/edit.blade.php
@extends('layouts.master')

@push('css')
    
@endpush

@section('content')

<div class="app-title">
    <div>
        <h1><i class="fa fa-user-plus"></i> Edit Department</h1>
    </div>
    <div>
        <a href="{{ route('department.index') }}" class="btn btn-dark">
            <i class="fa fa-arrow-left"></i> Back
        </a>
    </div>
</div>
  
<div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="tile">
        <div class="tile-body">
          
            <form action="{{ route('department.update', $employeeDepartment->id) }}" method="post">
                @csrf
                @method('PUT')

                <div class="form-group row">
                    <label class="col-md-3" for="department_name">Department Name <span class="text-danger">*</span> </label>
                    <div class="col-md-9">
                        <input type="text" name="department_name" id="department_name" value="{{ $employeeDepartment->department_name }}" class="form-control">
                        @error('department_name')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-3" for="department_description">Description </label>
                    <div class="col-md-9">
                        <textarea name="department_description" id="department_description" class="form-control">{{ $employeeDepartment->department_description }}</textarea>
                        @error('department_description')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-9 offset-md-3">
                        <input type="submit" value="Update" class="btn btn-primary">
                    </div>
                </div>

            </form>

        </div>
      </div>
    </div>
  </div>

@endsection

@push('js')

@endpush

resources/views/setting/department/index.blade.php
@extends('layouts.master')

@push('css')
    
@endpush

@section('content')

<div class="app-title">
    <div>
        <h1><i class="fa fa-users"></i> Employee Department</h1>
    </div>
    <div>
        <a href="{{ route('department.create') }}" class="btn btn-primary">
            <i class="fa fa-plus"></i> Add New Department
        </a>
    </div>
</div>

@if (session('message'))
    {!! session('message') !!}
@endif
  
<div class="row">
    <div class="col-md-12">
      <div class="tile">
        <div class="tile-body">
          <div class="table-responsive">
            <table class="table table-hover table-bordered" id="sampleTable">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Department Name</th>
                  <th>Description</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                @foreach ($departments as $key => $department)
                  <tr>
                    <td>{{ ++$key }}</td>
                    <td>{{ $department->department_name }}</td>
                    <td>{{ $department->department_description ?? '---' }}</td>
                    <td>
                        <div class="btn-group">
                            <a href="{{ route('department.edit', $department->id) }}" class="btn btn-info btn-sm">
                                <i class="fa fa-edit"></i>
                            </a>
                            @can('admin-only', Auth::user())
                            <form action="{{ route('department.destroy', $department->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="delete_button btn btn-danger btn-sm"> 
                                    <i class="fa fa-trash"></i> 
                                </button>
                            </form>
                            @endcan
                        </div>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

@endsection

@push('js')
<script type="text/javascript" src="{{ asset('assets/') }}/js/plugins/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="{{ asset('assets/') }}/js/plugins/dataTables.bootstrap.min.js"></script>
<script type="text/javascript" src="{{ asset('assets/') }}/js/sweetalert2@9.js"></script>
<script type="text/javascript">

    $('#sampleTable').DataTable();

    $(document).on('click', '.delete_button', function (e) {
        e.preventDefault();
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value) {
                $(this).closest('form').submit();
            }
        });
    });
</script>
@endpush